const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d');
const fadeLayer=document.getElementById('fadeLayer');
const tooltip=document.getElementById('tooltip');
const STATE={MENU:0,SCENE_1_CHAT:1,SCENE_1_PHONE:2,SCENE_2_DINNER:3,SCENE_3_WALK:4,ENDING:5};
const COLORS={bg:'#fffaf0',primary:'#ff8da1',xhs_red:'#ff2442',text:'#5d5d5d',highlight:'#ffb7c5',ui_gray:'#e0e0e0',phone_screen:'#f8f8f8',bubble_green:'#95ec69'};
let CONTENT=null;let ENDINGS=null;
let currentState=STATE.MENU;let score=0;let frameCount=0;let mouse={x:0,y:0,clicked:false};let textTyper={text:'',index:0,complete:false};let billTimer=0,walkTimer=0,showDinnerOptions=false,waiterX=600;let flags={sawMoments:false,paidSecretly:false,gaveCoat:false,scene1Finished:false,scene2Finished:false,scene3Finished:false};
async function loadConfig(){let c=null;let e=null;try{const r=await fetch('content.json');c=await r.json()}catch(_){c=null}try{const r2=await fetch('endings.json');e=await r2.json()}catch(_){e=null}if(!c){c={menu:{title:'恋雪',subtitle:'高清版',startButton:'开始恋雪',heart:'❤'},tooltip:{scene1Hint:'试试点开一条笔记来不是按钮的东西？'},profile:{nick:'橘生✨',status:'在校',xhsIdLabel:'小红书号：',xhsIdValue:'12345678'},scene1:{topbarTitle:'小红书',backLabel:'<',moreLabel:'...',cardLabel:'dd',optionLove:'你真美',optionAskName:'先认识你，请问你叫什么名字',optionWithLike:'先认识你并点赞，说明你一定很好记性',returnHomeButton:'返回主页',tabs:{note:'笔记',fav:'收藏',liked:'赞过'},pic1Title:'自拍一张 ~',pic1Likes:'❤ 1.2w',pic2Title:'探店 ...',feed:[{title:'清晨的雪',likes:'❤ 2.3w',image:'https://picsum.photos/seed/lx1/600/900'},{title:'咖啡与书',likes:'❤ 1.1w',image:'https://picsum.photos/seed/lx2/600/900'}]},scene2:{drinkLabel:'饮料',paidText:'已悄悄买单',msg1:'她：今天点得真不错 ~ 味道都不赖！',msg2:'（服务员开始结账单慢慢走来二人...）',msg3:'服务员：你们，请问这笔账单要AA吗？',afterPaidMsg:'我：既然从认识瞬间的时刻已经经过了。',optionPay:'我来买单',optionAA:'我们要AA吗？'},scene3:{msg1:'（走在回家的路上，灯光映着二人身影来...）',msg2:'她：嗯... 你真好...',msg3NoCoat:'我该问问...',msg3Coat:'我：（轻轻脱下外套披在她身上）',optionAskCold:'问她：你冷吗？',optionKeepWalking:'坚持一路走到家'},endingHeader:'恋雪结束'}}CONTENT=c;if(!e){e={endings:[{id:'perfect',minScore:5,title:'完美结局：这就是爱',desc:'爱不是说说而已，而是每一个细微处的体贴与守护。',color:'#ff8da1',symbol:'❤ ❤',symbolColor:'#ff8da1'},{id:'normal',minScore:2,title:'普通结局：好人卡',desc:'你是个好人，但可能还不足以感动她。',color:'#f39c12',symbol:'🙂',symbolColor:'#333'},{id:'bad',minScore:-999,title:'坏结局：直男癌',desc:'有些机会会错过，这才是真实的错过。',color:'#7f8c8d',symbol:'🙃',symbolColor:'#7f8c8d'}]}}ENDINGS=e;await preloadImagesFromContent(CONTENT)}
function resetGame(){score=0;frameCount=0;billTimer=0;walkTimer=0;showDinnerOptions=false;waiterX=600;flags={sawMoments:false,paidSecretly:false,gaveCoat:false,scene1Finished:false,scene2Finished:false,scene3Finished:false};resetTyper()}
function typeText(str,speed=2){if(textTyper.text!==str){textTyper.text=str;textTyper.index=0;textTyper.complete=false}if(!textTyper.complete){if(frameCount%speed===0)textTyper.index++;if(textTyper.index>=str.length)textTyper.complete=true}return str.substring(0,textTyper.index)}
function resetTyper(){textTyper.text='';textTyper.index=0;textTyper.complete=false}
function transitionTo(newState,callback){fadeLayer.classList.add('fade-active');setTimeout(()=>{if(callback)callback();currentState=newState;mouse.clicked=false;resetTyper();fadeLayer.classList.remove('fade-active')},1000)}
const DESIGN_W=900,DESIGN_H=600;function resize(){const scale=Math.min(window.innerWidth/DESIGN_W,window.innerHeight/DESIGN_H);const dpr=window.devicePixelRatio||1;canvas.style.width=(DESIGN_W*scale)+'px';canvas.style.height=(DESIGN_H*scale)+'px';canvas.width=DESIGN_W*dpr;canvas.height=DESIGN_H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize)
function drawRect(x,y,w,h,color,radius=0){ctx.fillStyle=color;ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,radius);else{ctx.moveTo(x+radius,y);ctx.arcTo(x+w,y,x+w,y+h,radius);ctx.arcTo(x+w,y+h,x,y+h,radius);ctx.arcTo(x,y+h,x,y,radius);ctx.arcTo(x,y,x+w,y,radius)}ctx.fill()}
function drawCircle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
function drawText(text,x,y,size,color=COLORS.text,align='center'){ctx.fillStyle=color;ctx.font=size+'px "ZCOOL KuaiLe", sans-serif';ctx.textAlign=align;ctx.fillText(text,x,y)}
function isHover(x,y,w,h){return mouse.x>x&&mouse.x<x+w&&mouse.y>y&&mouse.y<y+h}
function drawButton(text,x,y,w,h,callback,btnColor=COLORS.primary){const hover=isHover(x,y,w,h);if(hover)canvas.style.cursor='pointer';ctx.fillStyle=hover?btnColor:'#fff';ctx.strokeStyle=btnColor;ctx.lineWidth=3;ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,w,h,10);else drawRect(x,y,w,h,ctx.fillStyle,10);ctx.fill();ctx.stroke();let fontSize=18;if(text.length>12)fontSize=16;if(text.length>16)fontSize=14;if(text.length>20)fontSize=12;ctx.font=fontSize+'px "ZCOOL KuaiLe", sans-serif';ctx.textAlign='center';ctx.fillStyle=hover?'#fff':btnColor;ctx.fillText(text,x+w/2,y+h/2+fontSize/3);if(hover&&mouse.clicked){mouse.clicked=false;callback()}}
function drawBean(x,y,isGirl=false,emotion='normal'){ctx.save();ctx.translate(x,y);ctx.fillStyle='#fff';ctx.strokeStyle='#333';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(0,0,40,50,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#333';if(emotion==='happy'){ctx.beginPath();ctx.moveTo(-15,-5);ctx.lineTo(-5,-15);ctx.lineTo(5,-5);ctx.moveTo(15,-5);ctx.lineTo(25,-15);ctx.lineTo(35,-5);ctx.stroke()}else{drawCircle(-15,-10,3,'#333');drawCircle(15,-10,3,'#333')}if(isGirl||emotion==='shy'){ctx.fillStyle='#ffb7c5';ctx.globalAlpha=.6;ctx.beginPath();ctx.arc(-20,5,6,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(20,5,6,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}if(isGirl){ctx.fillStyle='#333';ctx.beginPath();ctx.arc(0,-10,42,Math.PI,0);ctx.fill();ctx.beginPath();ctx.arc(-40,10,10,0,Math.PI*2);ctx.fill()}ctx.restore()}
function getMousePos(evt){const rect=canvas.getBoundingClientRect();return{x:(evt.clientX-rect.left)*(DESIGN_W/rect.width),y:(evt.clientY-rect.top)*(DESIGN_H/rect.height)}}
canvas.addEventListener('mousemove',e=>{const p=getMousePos(e);mouse.x=p.x;mouse.y=p.y;canvas.style.cursor='default'});
canvas.addEventListener('mousedown',()=>{mouse.clicked=true});
canvas.addEventListener('touchstart',e=>{const p=getMousePos(e.touches[0]);mouse.x=p.x;mouse.y=p.y;mouse.clicked=true;e.preventDefault()},{passive:false})
function updateMenu(){ctx.fillStyle=COLORS.bg;ctx.fillRect(0,0,DESIGN_W,DESIGN_H);drawText(CONTENT.menu.title,DESIGN_W/2,250,80,COLORS.primary);drawText(CONTENT.menu.subtitle,DESIGN_W/2,300,24,'#aaa');const s=1+Math.sin(frameCount*.05)*.05;ctx.save();ctx.translate(DESIGN_W/2,150);ctx.scale(s,s);drawText(CONTENT.menu.heart,0,0,60,COLORS.primary);ctx.restore();drawButton(CONTENT.menu.startButton,DESIGN_W/2-100,400,200,60,()=>{transitionTo(STATE.SCENE_1_CHAT,resetGame)})}
let selectedFeedIndex=-1;
function updateScene1(){ctx.fillStyle='#ddd';ctx.fillRect(0,0,DESIGN_W,DESIGN_H);const px=DESIGN_W/2-150,py=50,pw=300,ph=500;drawRect(px,py,pw,ph,'#333',30);drawRect(px+10,py+10,pw-20,ph-20,COLORS.phone_screen,20);drawRect(px+10,py+10,pw-20,50,'#fff',20);ctx.fillRect(px+10,py+30,pw-20,30);drawText(CONTENT.scene1.topbarTitle,px+150,py+45,18,'#333');drawText(CONTENT.scene1.backLabel,px+30,py+45,20,'#333');drawText(CONTENT.scene1.moreLabel,px+270,py+40,20,'#333');drawRect(px+20,py+70,pw-40,30,'#f0f0f0',15);drawText('🔍 搜索 '+CONTENT.profile.nick+' 的笔记',px+30,py+92,14,'#888','left');const avatarX=px+20,avatarY=py+110,avatarR=20;drawCircle(avatarX+avatarR,avatarY+avatarR,avatarR,COLORS.xhs_red);drawText(CONTENT.profile.nick,px+90,avatarY+25,16,'#333','left');drawText(CONTENT.profile.status,px+90,avatarY+45,12,'#aaa','left');drawText(CONTENT.scene1.tabs.note,px+40,py+150,14,'#333','left');drawText(CONTENT.scene1.tabs.fav,px+120,py+150,14,'#aaa','left');drawText(CONTENT.scene1.tabs.liked,px+200,py+150,14,'#aaa','left');const gridX=px+20,gridY=py+170,gridW=pw-40,cardW=(gridW-10)/2,cardH=cardW*1.2;for(let i=0;i<(CONTENT.scene1.feed||[]).length;i++){const col=i%2;const row=Math.floor(i/2);const cx=gridX+col*(cardW+10);const cy=gridY+row*(cardH+10);const it=CONTENT.scene1.feed[i];drawRect(cx,cy,cardW,cardH,'#fff',10);const img=ASSETS[it.image];if(img)drawImageCover(img,cx,cy,cardW,cardH-30);else{ctx.fillStyle='#eee';ctx.fillRect(cx,cy,cardW,cardH-30)}drawText(it.title,cx+10,cy+cardH-18,12,'#333','left');drawText(it.likes,cx+cardW-10,cy+cardH-18,12,'#e74c3c','right');if(isHover(cx,cy,cardW,cardH)){canvas.style.cursor='pointer';if(mouse.clicked){mouse.clicked=false;selectedFeedIndex=i;currentState=STATE.SCENE_1_PHONE}}}
if(frameCount>60){const optY=py+ph-110,btnColor=COLORS.xhs_red,btnW=280,btnX=px+(pw-btnW)/2;drawButton(CONTENT.scene1.optionLove,btnX,optY,btnW,40,()=>{flags.scene1Finished=true;transitionTo(STATE.SCENE_2_DINNER)},btnColor);drawButton(CONTENT.scene1.optionAskName,btnX,optY+50,btnW,40,()=>{flags.scene1Finished=true;score+=0;transitionTo(STATE.SCENE_2_DINNER)},btnColor);if(flags.sawMoments){ctx.shadowBlur=10;ctx.shadowColor=COLORS.xhs_red;drawButton(CONTENT.scene1.optionWithLike,btnX,optY-50,btnW,40,()=>{score+=2;flags.scene1Finished=true;transitionTo(STATE.SCENE_2_DINNER)},btnColor);ctx.shadowBlur=0}}}
function updateScene1Phone(){ctx.fillStyle='rgba(0,0,0,.5)';ctx.fillRect(0,0,DESIGN_W,DESIGN_H);const px=DESIGN_W/2-150,py=50,pw=300,ph=500;drawRect(px,py,pw,ph,'#fff',30);drawRect(px+10,py+10,pw-20,100,'#ccc',20);ctx.fillRect(px+10,py+80,pw-20,30);drawCircle(px+40,py+110,35,COLORS.xhs_red);drawText(CONTENT.profile.nick,px+120,py+130,18,'#333','left');drawText(CONTENT.profile.xhsIdLabel+CONTENT.profile.xhsIdValue,px+120,py+150,12,'#aaa','left');drawRect(px+220,py+120,60,26,COLORS.xhs_red,13);drawText('关注',px+250,py+138,14,'#fff');const detailY=py+170;const it=(CONTENT.scene1.feed||[])[selectedFeedIndex]||CONTENT.scene1.feed?.[0];if(it){const img=ASSETS[it.image];drawRect(px+20,detailY,pw-40,ph-260,'#000',10);if(img)drawImageCover(img,px+20,detailY,pw-40,ph-260);drawText(it.title,px+30,py+ph-70,16,'#333','left');drawText(it.likes,px+pw-30,py+ph-70,14,'#e74c3c','right')}drawButton(CONTENT.scene1.returnHomeButton,px+50,py+430,200,40,()=>{flags.sawMoments=true;currentState=STATE.SCENE_1_CHAT},COLORS.xhs_red)}
function updateScene2(){if(mouse.clicked&&!flags.scene2Finished&&!showDinnerOptions){if(isHover(500,100,200,300)){flags.paidSecretly=true;score+=2;ctx.fillStyle=COLORS.highlight;ctx.globalAlpha=.5;ctx.fillRect(500,100,200,300);ctx.globalAlpha=1;drawText(CONTENT.scene2.paidText,600,200,20,COLORS.primary);mouse.clicked=false;return}}ctx.fillStyle='#fff8dc';ctx.fillRect(0,0,DESIGN_W,DESIGN_H);drawRect(200,400,400,200,'#8b4513',10);drawCircle(300,420,30,'#ddd');drawCircle(500,420,30,'#ddd');drawText(CONTENT.scene2.drinkLabel,300,425,12,'#aaa');drawBean(250,350,false);drawBean(550,350,true);ctx.fillStyle='#d2b48c';ctx.fillRect(550,150,150,100);drawText('收银台',625,200,16,'#fff');if(!flags.paidSecretly&&!showDinnerOptions){if(frameCount%60<30)drawCircle(625,140,5,COLORS.primary)}else if(flags.paidSecretly){drawText('✔',625,140,20,'green')}drawRect(100,50,600,100,'#fff',10);ctx.strokeStyle='#333';ctx.lineWidth=2;ctx.strokeRect(100,50,600,100);billTimer++;let msg='';if(billTimer<200)msg=CONTENT.scene2.msg1;else if(billTimer<400){msg=CONTENT.scene2.msg2;let wX=750-(billTimer-200);if(wX<600)wX=600;waiterX=wX;drawBean(wX,300,false);drawRect(wX-15,320,30,40,'#fff',2)}else{msg=CONTENT.scene2.msg3;showDinnerOptions=true}drawText(typeText(msg),400,100,20,'#333');if(showDinnerOptions){if(flags.paidSecretly){drawRect(100,50,600,100,'#fff',10);drawText(CONTENT.scene2.afterPaidMsg,400,100,20,'#333');if(billTimer>550)transitionTo(STATE.SCENE_3_WALK)}else{drawButton(CONTENT.scene2.optionPay,200,500,150,50,()=>{score+=1;transitionTo(STATE.SCENE_3_WALK)});drawButton(CONTENT.scene2.optionAA,450,500,150,50,()=>{score-=1;transitionTo(STATE.SCENE_3_WALK)})}}}
function updateScene3(){ctx.fillStyle='#2c3e50';ctx.fillRect(0,0,DESIGN_W,DESIGN_H);ctx.fillStyle='rgba(255,255,255,.5)';for(let i=0;i<10;i++){let x=(frameCount*2+i*100)%DESIGN_W;let y=(frameCount*1+i*50)%DESIGN_H;drawCircle(x,y,2,'#fff')}ctx.fillStyle='#34495e';ctx.fillRect(0,450,DESIGN_W,150);const centerX=DESIGN_W/2,charY=400;let shake=0;if(walkTimer>100)shake=Math.sin(frameCount*.5)*2;drawBean(centerX+60+shake,charY,true,'normal');ctx.fillStyle='#ffcccc';ctx.beginPath();ctx.ellipse(centerX+60+shake,charY+50,20,40,0,0,Math.PI*2);ctx.fill();drawBean(centerX-60,charY,false);let coatColor='#8e44ad';if(isHover(centerX-80,charY+10,40,80)&&!flags.gaveCoat&&walkTimer>100){coatColor='#9b59b6';canvas.style.cursor='pointer';if(mouse.clicked){flags.gaveCoat=true;mouse.clicked=false;score+=2}}if(!flags.gaveCoat){ctx.fillStyle=coatColor;ctx.beginPath();ctx.ellipse(centerX-60,charY+50,25,45,0,0,Math.PI*2);ctx.fill()}else{ctx.fillStyle='#bdc3c7';ctx.beginPath();ctx.ellipse(centerX-60,charY+50,20,40,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=coatColor;ctx.beginPath();ctx.ellipse(centerX+60+shake,charY+55,28,48,0,0,Math.PI*2);ctx.fill()}drawRect(100,50,600,100,'#fff',10);walkTimer++;let msg='';if(walkTimer<100)msg=CONTENT.scene3.msg1;else if(walkTimer<300)msg=CONTENT.scene3.msg2;else if(!flags.gaveCoat)msg=CONTENT.scene3.msg3NoCoat;else msg=CONTENT.scene3.msg3Coat;drawText(typeText(msg),DESIGN_W/2,100,20,'#333');if(walkTimer>=300&&!flags.gaveCoat){drawButton(CONTENT.scene3.optionAskCold,200,500,200,50,()=>{score-=1;transitionTo(STATE.ENDING)});drawButton(CONTENT.scene3.optionKeepWalking,450,500,200,50,()=>{score-=2;transitionTo(STATE.ENDING)})}else if(flags.gaveCoat&&walkTimer>450)transitionTo(STATE.ENDING)}
function pickEnding(){const arr=ENDINGS.endings.slice().sort((a,b)=>b.minScore-a.minScore);for(let i=0;i<arr.length;i++){if(score>=arr[i].minScore)return arr[i]}return arr[arr.length-1]}
function updateEnding(){ctx.fillStyle=COLORS.bg;ctx.fillRect(0,0,DESIGN_W,DESIGN_H);drawText(CONTENT.endingHeader,DESIGN_W/2,150,40,'#333');const ed=pickEnding();drawText(ed.title,DESIGN_W/2,250,30,ed.color);drawText(ed.desc,DESIGN_W/2,300,18,'#555');drawText(ed.symbol,DESIGN_W/2,350,60,ed.symbolColor);drawButton('重新开始',DESIGN_W/2-100,450,200,50,()=>{transitionTo(STATE.SCENE_1_CHAT,resetGame)})}
function loop(){frameCount++;ctx.clearRect(0,0,DESIGN_W,DESIGN_H);switch(currentState){case STATE.MENU:updateMenu();break;case STATE.SCENE_1_CHAT:updateScene1();break;case STATE.SCENE_1_PHONE:updateScene1Phone();break;case STATE.SCENE_2_DINNER:updateScene2();break;case STATE.SCENE_3_WALK:updateScene3();break;case STATE.ENDING:updateEnding();break}if(currentState===STATE.SCENE_1_CHAT&&!flags.sawMoments&&frameCount<300){tooltip.style.opacity=1;tooltip.innerText=CONTENT.tooltip.scene1Hint}else{tooltip.style.opacity=0}if(mouse.clicked)mouse.clicked=false;requestAnimationFrame(loop)}
loadConfig().then(()=>{resize();requestAnimationFrame(loop)})
const ASSETS={};
function drawImageCover(img,dx,dy,dw,dh){const iw=img.naturalWidth||img.width;const ih=img.naturalHeight||img.height;const r=Math.max(dw/iw,dh/ih);const sw=dw/r;const sh=dh/r;const sx=(iw-sw)/2;const sy=(ih-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,dx,dy,dw,dh)}
async function loadImage(url){return new Promise(res=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>res(img);img.src=url})}
async function preloadImagesFromContent(c){const urls=[];if(c.scene1&&Array.isArray(c.scene1.feed)){for(const it of c.scene1.feed){if(it.image)urls.push(it.image)}}const uniq=[...new Set(urls)];for(const u of uniq){try{ASSETS[u]=await loadImage(u)}catch(_){}}
